from django.db import models
from django.contrib.auth.models import User

class ControleProducao(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    modelo_producao = models.CharField(max_length=100)
    categoria_producao = models.CharField(max_length=100)
    inicio_producao = models.DateField()
    tipo_cult_plantada = models.CharField(max_length=100)
    area_cultivada = models.DecimalField(max_digits=10, decimal_places=2)
    mudas_plantada = models.IntegerField()
    quant_sementes = models.IntegerField()
    valor_muda = models.DecimalField(max_digits=10, decimal_places=2)
    fertilizante = models.CharField(max_length=100)
    tipo_fertil = models.CharField(max_length=100)
    quant_fertilizante = models.IntegerField()
    valor_unid_fertil = models.DecimalField(max_digits=10, decimal_places=2)
    defensivo = models.CharField(max_length=100)
    tipo_defensivo = models.CharField(max_length=100)
    quant_defensivo = models.IntegerField()
    valor_defensivo = models.DecimalField(max_digits=10, decimal_places=2)
    quant_agua = models.DecimalField(max_digits=10, decimal_places=2)
    custo_irrigacao = models.DecimalField(max_digits=10, decimal_places=2)
    preparo_solo = models.CharField(max_length=100)
    custo_pre_solo = models.DecimalField(max_digits=10, decimal_places=2)
    analise_solo = models.CharField(max_length=100)
    custo_anal_solo = models.DecimalField(max_digits=10, decimal_places=2)
    conser_solo = models.CharField(max_length=100)
    dat_colheta = models.DateField()
    quant_produzida = models.DecimalField(max_digits=10, decimal_places=2)
    quant_vendida = models.DecimalField(max_digits=10, decimal_places=2)
    val_unid_vendida = models.DecimalField(max_digits=10, decimal_places=2)
    tipo_armazen = models.CharField(max_length=100)
    cust_armazen = models.DecimalField(max_digits=10, decimal_places=2)
    cust_mao_obra = models.DecimalField(max_digits=10, decimal_places=2)
    manut_equipament = models.DecimalField(max_digits=10, decimal_places=2)
    cust_energia = models.DecimalField(max_digits=10, decimal_places=2)
    cust_transport = models.DecimalField(max_digits=10, decimal_places=2)
    regist_certificado = models.CharField(max_length=100)
    cust_certificado = models.DecimalField(max_digits=10, decimal_places=2)
    tipo_animal = models.CharField(max_length=100)
    quant_animal = models.IntegerField()
    tipo_alimento = models.CharField(max_length=100)
    quant_aliment = models.DecimalField(max_digits=10, decimal_places=2)
    valor_aliment = models.DecimalField(max_digits=10, decimal_places=2)
    saude_animal = models.CharField(max_length=100)
    cust_saude = models.DecimalField(max_digits=10, decimal_places=2)
    tipo_prod_animal = models.CharField(max_length=100)
    dat_venda_animal = models.DateField()
    quant_vend_animal = models.DecimalField(max_digits=10, decimal_places=2)
    venda_unit_animal = models.DecimalField(max_digits=10, decimal_places=2)
    certif_animal = models.CharField(max_length=100)
    cust_certif_animal = models.DecimalField(max_digits=10, decimal_places=2)
    observacao = models.TextField()

    def __str__(self):
        return f"ControleProducao {self.id} - {self.user.username}"